const randomTsCode = () => {
  const rand = Math.random();
  if (rand > 0.5) {
    return `console.log("This is a random ts code generated by AI");`;
  } else {
    return `console.error("Error: Random number was not greater than 0.5");`;
  }
};
